# Generated by Django 4.0.2 on 2022-02-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_site',
            name='url',
            field=models.CharField(max_length=128),
        ),
    ]
