# Generated by Django 4.0.2 on 2022-02-12 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_site_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=128)),
                ('news_url', models.CharField(max_length=128)),
                ('add_date', models.DateField(default=datetime.datetime.now)),
                ('news_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news_site')),
            ],
        ),
    ]
