# Generated by Django 4.0.2 on 2022-02-12 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
