# Generated by Django 4.0.2 on 2022-02-17 20:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_add_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveNews',
            fields=[
                ('save_id', models.AutoField(primary_key=True, serialize=False)),
                ('save_date', models.DateTimeField(default=datetime.datetime.now)),
                ('news_save', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_save', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
