# Generated by Django 4.0.2 on 2022-02-17 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_savenews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savenews',
            name='news_save',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_save', to='news.news'),
        ),
    ]
