# Generated by Django 4.0.2 on 2022-02-24 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_savenews_news_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_site', to='news.news_site'),
        ),
    ]
