# Generated by Django 4.0.2 on 2022-03-09 16:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_news_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='news_site',
            name='url',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('link_url', models.CharField(max_length=256)),
                ('link_title', models.CharField(max_length=128)),
                ('link_add_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
